### ISSUE TITLE
[Help] Any samples on how to authenticate an user (Google/Facebook/..) with Firebase?

### ISSUE THREAD

**Issue by garyng** [step-up-labs/firebase-authentication-dotnet#1]
Any examples on how to authenticate an user (Google/Facebook) to get an access token for Firebase?

or how to get the `oauth access token` in C#?
``` csharp
var facebookAccessToken = "<login with facebook and get oauth access token>";
```

Thanks! :smiley:

**Comment by bezysoftware** [comment]
Hi, 
I will add a sample for facebook login, but in the meantime you can use this SDK to the login: https://github.com/Microsoft/winsdkfb

**Comment by garyng** [comment]
Okay! Thanks!
Anyway, what sdk/lib can be used for Google login? Will the official Google.Net API works?

**Comment by bezysoftware** [comment]
Yes I use the official one, it should work fine - https://github.com/google/google-api-dotnet-client

**Comment by garyng** [comment]
Ok! Thanks! :smile:

**Comment by garyng** [comment]
Hi again!

For Google oauth authentication, any scopes needed? Or just any scopes will work?

**Comment by bezysoftware** [comment]
Finally I had time to add samples! For google you don't need any scopes afaik but I always add email and profile to be able to read some info about the user.

**Comment by garyng** [comment]
Awesome! 👍 👍 👍
