### ISSUE TITLE
AuthErrorReasons not complete?

### ISSUE THREAD

**Issue by itswisdomagain** [step-up-labs/firebase-authentication-dotnet#10]
These error messages were not converted to AuthErrorReasons:
EMAIL_EXISTS
WEAK_PASSWORD

**Comment by hardcodet** [comment]
I think I just got the login-related codes from the docs when I filed the original PR, while those seem to be related to registering an account. If the error reason flag is currently being evaluated during registration, that should definitely be in. You mind doing a PR?

**Comment by bezysoftware** [comment]
PR would be welcome 👍

**Comment by itswisdomagain** [comment]
Awesome. I made the PR. Cheers
