### ISSUE TITLE
Firebase UI (WPF + UWP + Xamarin)

### ISSUE THREAD

**Issue by bezysoftware** [step-up-labs/firebase-authentication-dotnet#100]
I started rewriting the FirebaseAuthentication.net library from scratch. I noticed that the payloads that the current version (v3) sends out are not the same as the Javascript version of the library and I wanted to unify it, possibly adding other providers along the way ( phone, apple, microsoft, etc.). It actually makes the whole flow significantly easier to use, because the API gives you the OAuth url to navigate the user to, and also automatically process the redirect uri at the end of the flow. This means you don't have to manually (or via extra package) communicate with Facebook and others to get the access_token to give to Firebase.

With this simplified flow it also started to make sense to build a UI on top of it - just like the official Firebase UI - that you could just drop to your design surface and it would handle everything for you. I currently have a working prototype for WPF, but I plan to to write a version for UWP and Xamarin as well. 

The code currently lives in [v4 branch](https://github.com/step-up-labs/firebase-authentication-dotnet/tree/feature/v4), but feel free to check it out and comment on the API. 

![image](https://user-images.githubusercontent.com/6108688/71259812-8f269580-2339-11ea-8628-f70110be3f74.png)

As you can see from the screenshot, it now supports 6 providers + anonymous, localization (35+ languages taken from Firebase repo) and native email flow. It is still missing some key pieces (e.g. credentials persistence is currently in-memory only) but it is usable for demo.

Please, let me know your thoughts, ideas, comments... in this issue

**Comment by bronquit** [comment]
Thank you for this - looking forward to FirebaseUI for Xamarin. Is it possible to include support for Xamarin Native as well? (Xamarin.Android and Xamarin.iOS without .Forms)

According to [this](https://github.com/step-up-labs/firebase-authentication-dotnet/tree/feature/v4#firebaseauthenticationnet) it sounds like [Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms) will be a dependency: 

> FirebaseAuthentication.Xamarin targets Xamarin.Forms

**Comment by bezysoftware** [comment]
Yes, that's the plan currently. But maybe there is a way to write it for Android and iOS separately and have it also work in a Forms app? I'll evaluate after I finish uwp version

**Comment by cabauman** [comment]
This looks amazing. Just now saw this issue. How's it coming along, since the original post?

**Comment by bezysoftware** [comment]
The UWP and WPF platforms are pretty much ready and can be used, but I haven't yet started Xamarin, too busy at work 😔

**Comment by cabauman** [comment]
I understand. Let me know if there's anything I can do to help.

**Comment by trevorm7** [comment]
I'm using 4.0.0-alpha.2 and the AuthStateChanged event isn't triggering after I sign in using email without any errors or exceptions.

**Comment by angelru** [comment]
what a great idea! I know it's very nice, let's see if it's ready for xamarin ...

**Comment by MO35AB** [comment]
is this project still working ? cant find the UI for wpf :(

**Comment by bezysoftware** [comment]
I haven't had time in the last months to spend on this project but the WPF version is here: https://www.nuget.org/packages/FirebaseAuthentication.wpf/

**Comment by bezysoftware** [comment]
Released
