### ISSUE TITLE
Getting "Could not load type" exception with simple User Signup. 

### ISSUE THREAD

**Issue by Nerves82** [step-up-labs/firebase-authentication-dotnet#103]
I am trying to do a simple user signup with the below code. I have imported the FirebaseAuthentication.net 3.4.0 Nuget package. I continue to get a "Could not load type" exception on the Firebase.Auth.FirebaseAuthProvider class. Do I need to pull in another Nuget to make this work?

Could not load type of field 'BaseApp.ViewModels.SignUpViewModel+<SignUp>d__25:<authProvider>5__1' (6) due to: Could not resolve type with token 010000b8 from typeref (expected class 'Firebase.Auth.FirebaseAuthProvider' in assembly 'Firebase.Auth, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Firebase.Auth, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:Firebase.Auth.FirebaseAuthProvider member:(null)

    private void SignUp()
            {
                 Task.Run(async () =>
                 {
                      if (string.IsNullOrEmpty(UserName) || string.IsNullOrEmpty(Password) || string.IsNullOrEmpty(Email) || string.IsNullOrEmpty(VerifyEmail))
                {
                    Acr.UserDialogs.UserDialogs.Instance.Alert("You forgot some information.");
                    return;
                }

                if (Email.Contains("@") == false)
                {
                    Acr.UserDialogs.UserDialogs.Instance.Alert("Email is incorrect format.");
                    return;
                }

                if (Email != VerifyEmail)
                {
                    Acr.UserDialogs.UserDialogs.Instance.Alert("Email and Verify Email do not match.");
                    return;
                }

                Email = Email.ToLower();
                try
                {
                    var user = await SignUp(Email, Password, UserName);

                    if (user != null)
                    {
                        DisplayAlert("Success", "Sign Up Successfull", "OK", () => { Navigation.PopAsync(); });
                    }
                    else
                    {
                        DisplayAlert("Not Success", "Sign Up Not Successfull", "OK", () => { Navigation.PopAsync(); });
                    }
                }
                catch (Exception e)
                {
                    Acr.UserDialogs.UserDialogs.Instance.Alert($"Error signing up: {e.Message}");
                }
            });
        }

    public async Task<User> SignUp(string email, string pw, string username)
        {
            try
            {
                var authProvider = new FirebaseAuthProvider(new FirebaseConfig("my api key is here"));
                var authLink = await authProvider.CreateUserWithEmailAndPasswordAsync(email, pw, username);

                return authLink.User;
            }
            catch (Exception ex)
            {
                Acr.UserDialogs.UserDialogs.Instance.Alert($"Error : {ex.Message}");
                return null;
            }
        }

**Comment by simonemontella** [comment]
@Nerves82 how did you solve? i've the same problem rn
