### ISSUE TITLE
How does one sign out a user?

### ISSUE THREAD

**Issue by Nerves82** [step-up-labs/firebase-authentication-dotnet#104]
Hi. I am having trouble discovering the code snippet to sign out a user. Can someone share that with me? Thanks.

**Comment by DooblyNoobly** [comment]
I just came here looking for the same thing

**Comment by DooblyNoobly** [comment]
see #61 I guess I will need to do it in the admin sdk

**Comment by bezysoftware** [comment]
I highly recommend checking out the v4 preview currently being developed in [feature/v4](https://github.com/step-up-labs/firebase-authentication-dotnet/tree/feature/v4#firebaseauthenticationnet-1) branch. It aligns the API with the official Javascript counterpart giving you the `SignOutAsync` method.
It also gives you FirebaseUI for UWP + WPF (Xamarin is coming)

**Comment by LeoJHarris** [comment]
@bezysoftware exactly what I was looking for as well 👍  looking forward to v4 going stable 🥇
