### ISSUE TITLE
Service account vs Api Key

### ISSUE THREAD

**Issue by nhwilly** [step-up-labs/firebase-authentication-dotnet#107]
Great package, thanks for it.

To be clear, is it correct to say that if I want to get the Firebase tokens (which I need using your package) **and** I want to update items via the service account, I have to have two different sets of credentials and use both packages independently?

I've got it working now (was super confused for an hour or two) and I've done it with two Json files.

Have I got this right?

TIA

**Comment by bezysoftware** [comment]
Can you share details about your implementation?
