### ISSUE TITLE
Using this for WPF apps on .NET Framework

### ISSUE THREAD

**Issue by nmggithub** [step-up-labs/firebase-authentication-dotnet#109]
Hello,

I installed FirebaseAuthentication.NET v4 into my WPF app project, and that worked. I then tried to install FirebaseAuthentication.WPF, which did not work. I see now it's because it targets .NET Core. My app targets the .NET Framework. Is the FirebaseAuthentication.WPF package unnecessary for WPF apps that target the .NET Framework?

**Comment by bezysoftware** [comment]
The WPF library adds the UI portion of Firebase Authentication (email flow, web browser popup etc). If you don't need this / can implement it on your own, then you don't need to WPF library
