### ISSUE TITLE
A step by step CRUD  Example on Firebase and DeveExpress

### ISSUE THREAD

**Issue by huxaiphaer** [step-up-labs/firebase-authentication-dotnet#11]
Hello thanks for your documentation , but please help us we beginners and make for us a simple step by step Example on this . It would be our pleasure thanks.

**Comment by bezysoftware** [comment]
You already have samples:
https://github.com/step-up-labs/firebase-authentication-dotnet/tree/master/samples/Social
https://github.com/step-up-labs/firebase-database-dotnet/tree/master/samples
and two blog posts
http://blog.bezysoftware.net/firebase-csharp-library/
http://blog.bezysoftware.net/firebase-authentication-csharp-library/

**Comment by huxaiphaer** [comment]
Thanks for the reply , but isn't there more simpler examples such as
sending data to databse and retrieving in the list with jsut a sing TextBox
or a List?

Thanks .
