### ISSUE TITLE
does function OpenBrowserAndWaitForRedirectToAuthDomain exists?

### ISSUE THREAD

**Issue by taruyar** [step-up-labs/firebase-authentication-dotnet#110]
I 've found this awesome library(v4 in particular), and try to utilize this for my WPF application.

According to [your post](https://medium.com/step-up-labs/firebaseui-for-net-wpf-uwp-xamarin-553abc5da3f), there's some function named **OpenBrowserAndWaitForRedirectToAuthDomain**, 

I've looked over your codes, and didn't find it.
Is this gonna be implemented in near future?
Or is this supposed to be implemented by each developer?

Thanks in advance!

**Comment by bezysoftware** [comment]
It depends on your scenario. If you plan on using the WPF library, no need to implement it, the WPF library already has it's own implementation.

The `SignInWithRedirectAsync` would typically be handled by platform libraries (UWP/WPF/Xamarin), and not by end developers.
