### ISSUE TITLE
Does this package support multi-tenancy?

### ISSUE THREAD

**Issue by mohed** [step-up-labs/firebase-authentication-dotnet#111]
Hi, thank you for a great library.

I need to implement multi-tenancy and I was looking for a way to use this library with the option to specify a tenant. I cant find any functionality in the code. Is multi-tenancy supported?

I tried extending the FirebaseAuthProvider and hiding the `SignInWithEmailAndPasswordAsync()`  method and providing my own implementation but because of private access modifiers on many of the fields it got messy and I abandoned the idea.

**Comment by GiampaoloGabba** [comment]
i suppose this got lost duraing the rewrite for 4.0 :(
