### ISSUE TITLE
400 BadRequest - SendEmailVerificationAsync(auth)

### ISSUE THREAD

**Issue by R41z0r** [step-up-labs/firebase-authentication-dotnet#114]
Hi  there,

every time I start using SendEmailVerificationAsync(auth) it's working for the first time, subsequent uses get a 400 http status code, could it be possible, that there is a quota limit on how many mails per user are allowed? Because you are not correctly handle that if so.

Exception:
"exception": {
    "type": "System.Net.Http.HttpRequestException",
    "message": "Response status code does not indicate success: 400 (Bad Request).",
    "stackTrace": "  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs:168 \n  at Firebase.Auth.FirebaseAuthProvider.SendEmailVerificationAsync (System.String firebaseToken) [0x000c4] in <b7d30080e5c84cdd89fecccebee7d186>:0 \n  at Firebase.Auth.FirebaseAuthProvider.SendEmailVerificationAsync (Firebase.Auth.FirebaseAuth auth) [0x00076] in <b7d30080e5c84cdd89fecccebee7d186>:0 \n  at PoleOase.LoginPage.Login (System.Object sender, System.EventArgs e) [0x00c1b] in <PATH>",
    "wrapperSdkName": "appcenter.xamarin"
  },

Easy to reproduce, just use the function many times in a row and you have that error.

**Comment by gdarmon** [comment]
make sure you have your database rules 
"rules": {  
    ".read": "auth==null",  
    ".write":"auth==null"  
  }

**Comment by R41z0r** [comment]
Thanks for your answer, but the problem is a timer. I proved it, you re
only possible to send a mail ones in a minute, if I wait a minute, there is
no error. If I would do it like you said, my database is insecure. As I
said, it's working the way it is only problem is you'll get a 400 if you
send to many mails (more than 1/minute).

I have built a workaround for that, so if you think the problem is only in
my instance just close the ticket.

Gilad Darmon <notifications@github.com> schrieb am Sa., 2. Mai 2020, 23:37:

**Comment by Kibsgaard** [comment]
Yes, there are quotas:
https://firebase.google.com/docs/auth/limits

There also appear to be stricter short-term limits on e.g. SendEmailVerificationAsync to prevent spamming and using up your entire quota. E.g. programming errors that keeps sending emails until the user is verified could use up your spark plan quota in a couple of seconds without this limit.

@R41z0r can you make a pull request with try/catch similar to the other functions in FirebaseAuthProvider.cs?
The case also needs to be added to GetFailureReason(..) and AuthErrorReason.cs.

@gdarmon that is really bad advise. That would leave your entire database open for anyone on the internet to read and edit. Please never do this.
