### ISSUE TITLE
Signout function not found?

### ISSUE THREAD

**Issue by emin-karadag** [step-up-labs/firebase-authentication-dotnet#115]
Hello,
Hello there,
I have completed the e-mail registration process via Firebase Auth Provider.
However, I cannot log out via FirebaseAuthProvider. I couldn't find the function.
Could you help?
Thanks... :)

**Comment by HassanSiddique** [comment]
@emin-karadag  how you tackle the sign out Issue ? I have the same problem. 

Thanks
