### ISSUE TITLE
Google cloud function

### ISSUE THREAD

**Issue by Poselsky** [step-up-labs/firebase-authentication-dotnet#117]
So every time user registers, I want to keep database updated with firebase functions.
The problem is, that user().onCreate handler gets displayName property set to null. 

How cloud function looks like: 
(Please, ignore that photoUrl property. I know that it shouldn't be there)
![cloudFunction](https://user-images.githubusercontent.com/45047700/80918684-8a053880-8d66-11ea-8d9e-6edbf9a57362.PNG)

When logging in, I can retrieve the display name.
![UsrNameExists](https://user-images.githubusercontent.com/45047700/80918729-c6389900-8d66-11ea-8bb1-09d5e49d3af2.PNG)

Response from server when registered.
![null](https://user-images.githubusercontent.com/45047700/80918742-cfc20100-8d66-11ea-9788-5ee1af41b8db.PNG)

I suspect that [it has to do with this.](https://github.com/step-up-labs/firebase-authentication-dotnet/blob/fc2d8117213f768a64b360829eedd9edc702c6ce/src/Firebase.Auth/FirebaseAuthProvider.cs#L194) Instead of updating the user after signing in, it should create user with the display name right away.

I can create PR if issue is accepted.

**Comment by bezysoftware** [comment]
Can you verify this happens also with the v4 of the library?
