### ISSUE TITLE
Sign In With Apple (Apple Guidelines)

### ISSUE THREAD

**Issue by mtsrdr** [step-up-labs/firebase-authentication-dotnet#119]
Any plans to add Sign In With Apple?

According to Apple's Guidelines app updates must follow these guidelines starting June 30, 2020

### 4.8 Sign in with Apple
https://developer.apple.com/sign-in-with-apple/get-started/
https://developer.apple.com/app-store/review/guidelines/#sign-in-with-apple
> Apps that use a third-party or social login service (such as Facebook Login, Google Sign-In, Sign in with Twitter, Sign In with LinkedIn, Login with Amazon, or WeChat Login) to set up or authenticate the user’s primary account with the app must also offer Sign in with Apple as an equivalent option. A user’s primary account is the account they establish with your app for the purposes of identifying themselves, signing in, and accessing your features and associated services.

**Comment by raymonderasmus** [comment]
I am having the same issue.

**Comment by CharlesGlass** [comment]
Is there anything on the roadmap to add this?

**Comment by bezysoftware** [comment]
v4 (https://github.com/step-up-labs/firebase-authentication-dotnet/tree/feature/v4) should have support for Apple Id

**Comment by CharlesGlass** [comment]
> v4 (https://github.com/step-up-labs/firebase-authentication-dotnet/tree/feature/v4) should have support for Apple Id

Do we have an ETA on this development?

**Comment by Kapusch** [comment]
Hello @bezysoftware , I'm using your latest official release for 6 months and everything works fine.
Again, great thanks for your library.

Unfortunately, my app just got rejected by Apple verification team because "Apple Sign In" is missing.

- Do I have to migrate to your pre-release ?
- Do you have an ETA for v4 ?

**Comment by bezysoftware** [comment]
@Kapusch unfortunately I don't, I don't have that much time to dedicate to Firebase Auth anymore. Alpha of v4 is currently on Nuget and should be mostly usable though
