### ISSUE TITLE
Can't retrieve UserCredential object from localstorage in v4

### ISSUE THREAD

**Issue by ellipsis-apps** [step-up-labs/firebase-authentication-dotnet#122]
I'm using v4 (.net core 3.x) in a Blazor WASM application. I can successfully register a user, and get back a valid UserCredential object. However, when I serialize it, to try to store it in localstorage and then retrieve it, the User property is empty. 
I believe it is because the User class constructor is internal, and that is messing up the Json deserialization.

What is the reasoning behind making the constructor internal rather than public?

**Comment by bezysoftware** [comment]
Take a look at the UWP / WPF repositories - https://github.com/step-up-labs/firebase-authentication-dotnet/blob/feature/v4/src/Auth.UI.UWP/Repository/StorageRepository.cs
I suggest writing something similar to this for your Blazor app
