### ISSUE TITLE
How to log in with another account?🤔

### ISSUE THREAD

**Issue by StarKen0617** [step-up-labs/firebase-authentication-dotnet#123]
Hello, I would like to know how I could log in with another google account, since I log in with one, but now it won't let me log in with another once I click on "Sign in with google"

**Comment by bezysoftware** [comment]
Unfortunately the WebView remembers the last logged in user and I am not sure how to force it to forget it, it will need to be investigated

**Comment by awardhana-bp** [comment]
with google, I am able to sign out via an Url
`await WebAuthenticationBroker.AuthenticateAsync(window, provider, "https://www.google.com/accounts/Logout", "");`

however this only applies to google so would still be best if we have a way to clear the cookies
