### ISSUE TITLE
Xamarin.Forms FirebaseConfig Hangs UI on IOS

### ISSUE THREAD

**Issue by mertozal** [step-up-labs/firebase-authentication-dotnet#125]
I'm using this library for my xamarin.forms project. It works without any problem on Android but hangs on IOS without any error. After i check step by step, i find out FirebaseConfig is hangs UI when creating FirebaseAuthProvider.  Code is like this:
`FirebaseAuthProvider auth = new FirebaseAuthProvider(new FirebaseConfig(Helpers.ApiKeys.firebaseApiKey));`
When i make `FirebaseAuthProvider auth = null;` it works perfectly (ofc without creating auth provider) but its not make sense..

**Comment by Transferr3** [comment]
I reinstalled library couple times. No luck. Is there any thing we need to do for this library after download ?

**Comment by sylverbee** [comment]
I confirm the bug on iOS.
I used @mertozal solution to setup FireBaseAuthConfig correctly

`FirebaseAuthProvider Provider = null;
Provider = new EmailProvider();
var config = new FirebaseAuthConfig
{
    ApiKey = "blabla",
    AuthDomain = "blabla.firebaseapp.com",
    Providers = new FirebaseAuthProvider[]
    {
        Provider
    }
};`
