### ISSUE TITLE
Cannot extend session with GetFreshAuthAsync() method 

### ISSUE THREAD

**Issue by Kapusch** [step-up-labs/firebase-authentication-dotnet#127]
Hello,

I have been using your great library from the first day I had to plug Firebase to my Xamarin app, and it's a pleasure to see that everything works well everyday.

I am currently able to Sign Up/Sign In via Email, Google & Facebook.
However, I'm a bit confused about **how to extend the session of an authenticated user who re-opens his app after a while**.

After my user is authenticated, I store the FirebaseAuthLink object in a secure storage. And because the serialization apparently does not work for internal properties, I have to re-create a FirebaseAuthLink when I retrieve my stored auth user.

This is how I achieve this :
```
    FirebaseAuthLink authLink = new FirebaseAuthLink(myValidAuthProvider, myStoredAuthUser);
    FirebaseAuthLink refreshedAuthUser = await authLink.GetFreshAuthAsync();

    // ....
    // But I also gave a try to this way :
    // FirebaseAuthLink refreshedAuthUser = await myValidAuthProvider.RefreshAuthAsync(myStoredAuthUser);
```

**But the GetFreshAuthSync() method does not return anything, not even an exception.**

I have grabbed the code from your repo in order to go deeper in the debug mode, and I was able to get the response content from the code below :
![image](https://user-images.githubusercontent.com/9576733/88482628-c8c01e80-cf62-11ea-9aee-69f2569d2dbf.png)

And here is the content of "responseData" :
![image](https://user-images.githubusercontent.com/9576733/88482510-ee98f380-cf61-11ea-8915-10992325cb3b.png)

- Could you please help me finding what I'm doing wrong here ?
- Or do you know another way to extend the current auth session ?

Thanks in advance !

My configuration :
-------------------------------
- Visual Studio for Mac (8.6.7)
- Xamarin.Forms (4.7.0.1142)
- FirebaseAuthentication.net (3.4.0)
- iPhone Simulator & Physical Device (iOS 13.6)

**Comment by Kapusch** [comment]
Hi,

I am very sorry to ping you @itswisdomagain , but do you have some clues on this issue please ?

I really would like to implement this feature in my app before I release it.

**Comment by itswisdomagain** [comment]
> because the serialization apparently does not work for internal properties, I have to re-create a FirebaseAuthLink when I retrieve my stored auth user

I _think_ that's where the problem is coming from. To confirm, can you try `GetFreshAuthSync()` **immediately** after authenticating a user?

**Comment by Kapusch** [comment]
I was able to reproduce your [integration test](https://github.com/step-up-labs/firebase-authentication-dotnet/blob/fc2d8117213f768a64b360829eedd9edc702c6ce/src/Firebase.Auth.Tests/IntegrationTests.cs#L179) : GetFreshAuthSync() returns a new token if immediately called after authenticating user.

I have to find how to to retrieve my FirebaseAuthLink object without serializing it.

**Comment by Kapusch** [comment]
I've made GetFreshAuthSync() work in my auth session management by doing two things :

- replacing SecureStorage from Xamarin.Essentials, by [XF Application.Properties](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.application.properties?view=xamarin-forms)
- loading authuser from local storage and then apply GetFreshAuthSync() on it, instead of recreating FirebaseAuthLink object (this was proposed [in this PR comment](https://github.com/step-up-labs/firebase-authentication-dotnet/pull/14))


Not sure if both have solved my problem, but anyway, it works !

Thanks @itswisdomagain .

**Comment by Kapusch** [comment]
Short update : it doesn't matter having SecureStorage or Application.Properties, both are working !

But I prefer to use SecureStorage from Xamarin.Essentials because data persists in the keychain, and then I'm able to retrieve my data, even if I reboot my app.
