### ISSUE TITLE
Question: Authentication failure with Google UserCredential AccessToken

### ISSUE THREAD

**Issue by BourgeoisDirk** [step-up-labs/firebase-authentication-dotnet#129]
For some reason I can't get past authentication, keep getting this error response: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential."
It fails on SignInWithOAuthAsync(), while i am using a valid Google.Apis.Auth.OAuth2.UserCredential

![image](https://user-images.githubusercontent.com/51524225/90010777-c5d26700-dca0-11ea-8056-c3f5d3b489c1.png)

I can't figure out what i'm doing wrong, any suggestions ?

**Comment by BourgeoisDirk** [comment]
The UserCredential works fine for GMail and Google Drive, but trying to log into Firebase with it keeps failing like this.
My user is set as Owner in Firebase, so really not seeing why this fails ..

**Comment by bezysoftware** [comment]
From the screenshot it doesn't seem youre using FirebaseAuthentication.net library

**Comment by BourgeoisDirk** [comment]
I am, it's just been renamed with a global using as such:
using GoogleFirestoreAuth = global::Firebase.Auth;

![image](https://user-images.githubusercontent.com/51524225/90330964-5a92d880-dfb1-11ea-862c-7db01bc9f260.png)

**Comment by BourgeoisDirk** [comment]
Dear Dev,

Could it possibly be that the problem occurs because my OAuth Client isn't limited to an Android or iOS app ?
![image](https://user-images.githubusercontent.com/51524225/90334673-a9e80180-dfcf-11ea-9e76-43856219aa91.png)

My App has a WPF, Android, and iOS interface, all using the same OAuth Client of type "Other", this is the one being used as everything goes over a web interface:
![image](https://user-images.githubusercontent.com/51524225/90334706-dbf96380-dfcf-11ea-9a74-c41cc984bdbe.png)

This OAuth Client does work perfectly for everything else from google, on all platforms. So why wouldn't it for FirebaseAuthentication.net ?

I mainly need this to get the desktop WPF interface running (the Android and iOS are still in development), so i can't limit my OAuth Client to one or the other, they all use the same web client.
