### ISSUE TITLE
User.IsEmailVerified remains false even though User verified account

### ISSUE THREAD

**Issue by JamesDepret** [step-up-labs/firebase-authentication-dotnet#134]
I'm using the SignInWithEmailAndPasswordAsync function and get the user returned. All the user properties are given correctly except the **IsEmailVerified**, which remains false, even though the testuser (me) has clicked on the verification mail, and received the message:

**Your email has been verified**
You can now sign in with your new account

For my code I have:

```C#
var authProvider = new FirebaseAuthProvider(new FirebaseConfig(_config["MyApp.FirebaseConfig"]));
var auth = await authProvider.SignInWithEmailAndPasswordAsync(interprocUser.Email, password);
if(auth != null)
{
       return auth.User.IsEmailVerified;               //<----- this value is always false 
}
```

**Comment by JamesDepret** [comment]
I say in the interface a call for GetUserAsync, so tried that out and in that object I do get the correct value for **IsEmailVerified**

This seems like it's a bug, but is bypassable this way?

```C#
var authProvider = new FirebaseAuthProvider(new FirebaseConfig(_config["InterProc.FirebaseConfig"]));
            var auth = await authProvider.SignInWithEmailAndPasswordAsync(interprocUser.Email, password);
            if(auth != null)
            {
                var user = await authProvider.GetUserAsync(auth);
                return user.IsEmailVerified;                
            }
```

**Comment by maltezc** [comment]
you've probably already solved this but i ran into the same issue earlier this week. 

you need to call `auth.RefreshUserDetails();`

for example, your code would be something like: 
            `var auth = await authProvider.SignUpWithEmailAndPasswordAsync(interprocUser.Email, password).ContinueWith(task =>

{
if (task.IsCompleted)
                {
                    authLink = task.Result;
                    authLink.isEmailVerified // <-- will return false because you just signed up. 
                   
                }
}`

// go and click the link

// then refresh user details.
`auth.RefreshUserDetails();
`
// check the status
`string status = auth.IsEmailVerified
`


It should be good after that.

**Comment by Kapusch** [comment]
Hi, I'm pretty sure this is not required anymore with this PR #112 (published to NuGet on 30 January).

If updating NuGet did not solve your issue, then you may want to have a look at #21
