### ISSUE TITLE
Web browser DOES NOT OPEN or OPEN FOR ONE TIME using firebase SignInWithOAuth from .net desktop application

### ISSUE THREAD

**Issue by HishamMokdad** [step-up-labs/firebase-authentication-dotnet#139]
Hello everybody
I am building a C# desktop application that aims to authorize a firebase user using his google account (gmail).
The problem is that the below code opens the browser irregularly, means that sometimes the browser -( Containing the emails in order for the user to choose one of them to login)- opens, and other times does not open.
Knowing that although the browser does not open in some cases, but the google account (may be the last used on this browser) is registered in firebase after calling the function. 
I need to open the browser anytime I call the function so that the user can know which google account he is chosen.

This is the code: 

        private async void GoogleClick()
        {
            try
            {
                var result = await GoogleWebAuthorizationBroker.AuthorizeAsync(
                    new ClientSecrets { ClientId = GoogleClientId },
                    new[] { "email", "profile" },
                    "user",
                    CancellationToken.None);

                if (result.Token.IsExpired(SystemClock.Default))
                {
                    await result.RefreshTokenAsync(CancellationToken.None);
                }

                this.FetchFirebaseData(result.Token.AccessToken, FirebaseAuthType.Google);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }

        private async void FetchFirebaseData(string accessToken, FirebaseAuthType authType)
        {
            try
            {
                // Convert the access token to firebase token
                var auth = new FirebaseAuthProvider(new FirebaseConfig(FirebaseAppKey));
                var data = await auth.SignInWithOAuthAsync(authType, accessToken);

                // Setup FirebaseClient to use the firebase token for data requests
                var db = new FirebaseClient(
                       FirebaseAppUri,
                       new FirebaseOptions
                       {
                           AuthTokenAsyncFactory = () => Task.FromResult(data.FirebaseToken)
                       });

            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }

This is the dialog that I want to appear anytime the user click on the "Sign in with Google" button:
![1](https://user-images.githubusercontent.com/74630266/100634283-c5d1a200-3337-11eb-8e6e-919c09e8cd1e.png)

**Comment by bezysoftware** [comment]
I would recommend using v4 which has FirebaseUI built-in. Working with `WebAuthorizationBroker` is a pain
