### ISSUE TITLE
AuthStateChanged not called on Email - Password Sign in.

### ISSUE THREAD

**Issue by Avrohom** [step-up-labs/firebase-authentication-dotnet#143]
I am trying to use the WPF version. 

If signing in with a provider such as Google than the `AuthStateChanged` gets called with the anticipated credentials.
Same is when Signing **UP** with a **NEW** email and password. But on successive sign in's with **already** registered email and passwords nothing seems to be happening.

**Comment by Mrquik** [comment]
Any update on this or a good workaround? I'd really like to use email login in my application.

**Comment by Avrohom** [comment]
Have a kook at my forked branch. I couldn't compile it, cause some issues with the build.
