### ISSUE TITLE
Error while creating the auth provider.

### ISSUE THREAD

**Issue by TheodorProject** [step-up-labs/firebase-authentication-dotnet#157]
![FirebaseAuth](https://user-images.githubusercontent.com/88656998/128784287-fd29203e-064f-44e9-8ef5-612acdf53e18.png)

I am getting this error while creating the auth provider. Therefore I cannot go ahead and use the various methods underlying this class.

**Comment by bezysoftware** [comment]
I would suggest following the code samples in the readme

**Comment by tride258** [comment]
identitytoolkit googleapis is no longer supported and all authentication methods except mail + password do not work
