### ISSUE TITLE
How to send emailprovider verification email

### ISSUE THREAD

**Issue by LordChunder** [step-up-labs/firebase-authentication-dotnet#158]
Im struggling trying to figure out how to send the email verification email for a newly signed up user.

Can anyone put me in the right direction? is there even a function for this in this library?

**Comment by tride258** [comment]
var auth = await authProvider.CreateUserWithEmailAndPasswordAsync (email, password, username,! true !, null);
you need to specify true or false which means to send or not. And you also need to enable the send function in firebase

**Comment by LordChunder** [comment]
Thank you so much!
