### ISSUE TITLE
"Unable to process request due to missing initial state"

### ISSUE THREAD

**Issue by DerKO9** [step-up-labs/firebase-authentication-dotnet#185]
I have forked/cloned the repo and tried running the console app sample. I have added my API key and auth domain to the config.
I run the app and choose Google as my provider. It gives me the URI and I paste it into Chrome.

It recognizes the auth domain and shows me all my google accounts I can login into (the black box is the censor my other accounts)
![image](https://user-images.githubusercontent.com/17974177/211243044-13a9a3df-c520-441c-8475-8f773fc0d2dc.png)

When I click on my account, It brings me to a page with an error message "Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared."
![image](https://user-images.githubusercontent.com/17974177/211242909-57c2dcce-e0fa-4f18-ac24-d4691888887e.png)

Is there something I'm missing in my setup to allow this to work?

**Comment by bezysoftware** [comment]
Which platform, what OS version?

**Comment by DerKO9** [comment]
I am on Windows 10 (x64) build 19044.2364
I built and ran Auth.Console.Sample in Visual Studio Code 2022 (latest update)
The URI was opened in Chrome Version 108.0.5359.125 (latest update)

The only code change is updating key and auth domain
![image](https://user-images.githubusercontent.com/17974177/211393161-dfb8d8ec-85d4-4c6b-858a-b03ca1d1f29c.png)

**Comment by bezysoftware** [comment]
That's a rather unfortunate message from Google, but otherwise this is expected. When you see that, copy-past the result url from browser back to console, which will finish sign-in

**Comment by DerKO9** [comment]
Oh wow, I apologize for not even trying to paste the url to see if it would work. I have just copy-pasted the url back into the console app and it signed me in successfully. Thank you!

Do you know of a way to automate this process? My project is winforms so I cannot use the convenient FirebaseUI to log my users in and will likely need to use this `client.SignInWithRedirectAsync()` method. It would be nice if my users didn't have to manually copy and paste the url to sign in.

I have tried `Process.Start(uri);` to open the url in the user's default browser, but I have no idea how I would get the returned url after they sign in.

**Comment by bezysoftware** [comment]
You can try looking at the other UI implementations (WPF & UWP) - they do this - open WebView, listen for this redirect uri and take it automatically. The platform-UI projects are not that code-heavy, largest chunk of work is for supporting email sign in (which needs to be native on each platform).
I am planning adding support for other platforms (e.g. Maui) but I do not have the capacity to take them on anytime soon

**Comment by DerKO9** [comment]
Alright, I will take a look! Thanks again for your help!

**Comment by bezysoftware** [comment]
I raised #186 to track any progress
