### ISSUE TITLE
Email & Password Account Verification Emails

### ISSUE THREAD

**Issue by tigerepic77** [step-up-labs/firebase-authentication-dotnet#187]
Before version 4 the package had the ability to send an email verification email, but after I've updated to version 4 there is no such function. Will you be adding this function back? If not i'd be interested to know why. Thanks

**Comment by bezysoftware** [comment]
I might add it when I have time, but since I don't need this feature, it's pretty low on my list. PRs welcome though

**Comment by tigerepic77** [comment]
Ah fair enough. Love the package though, big thanks to everyone making it!
