### ISSUE TITLE
Phone Authentication

### ISSUE THREAD

**Issue by abdu292** [step-up-labs/firebase-authentication-dotnet#198]
Can any one point me to a sample that's done with Phone Authentication?

We trying to build the web version of our Flutter mobile apps where the auth is implemented with Firebase Phone auth. 
We are using Blazor WASM for the web version.  Thanks a bunch!

**Comment by hardeep3** [comment]
Did you find a solution for that. I'm looking for the similar Firebase Phone Auth in Windows Desktop application.

**Comment by abdu292** [comment]
No, I haven’t. I’ve now switched to Flutter Web, which has built-in support for this. Thanks!
