### ISSUE TITLE
authLink.User.IsEmailVerified false despite verification

### ISSUE THREAD

**Issue by hardcodet** [step-up-labs/firebase-authentication-dotnet#21]
I triggered an email verification email through the library, got the email from FB, clicked it and got confirmation. However, when I now sign in with email and password, the IsEmailVerified flag is still false.

**Comment by itswisdomagain** [comment]
Interesting. I'm gonna test it and see if I can figure out what's causing the issue.
Thanks for the catch!

**Comment by hardcodet** [comment]
Repro:

                var authLink = await authProvider.SignInWithEmailAndPasswordAsync(email, password);
                User user = await authProvider.GetUserAsync(authLink.FirebaseToken);

The IsEmailVerified flag in authLink.User is false. The flag in the user that I retrieve in the second call is true.

**Comment by kashifiqbal112** [comment]
hi i have same issue can you resolve it ?

**Comment by yehyatt** [comment]
You should refresh the user object after verification as follows :

usertask = mAuth.getCurrentUser().reload();
usertask.addOnSuccessListener(new OnSuccessListener<Void>() {
    @Override
    public void onSuccess(Void aVoid) {
        user  = mAuth.getCurrentUser();
        boolean useremailveri = user.isEmailVerified();
        String useremailuid = user.getUid();
    }
});

**Comment by drptbl** [comment]
Workaround (you have to call `.GetUserAsync` after authenticating user in app with `.SignInWithEmailAndPasswordAsync`).
```csharp
AuthSvc.Auth = await Task.Run(() => AuthSvc.AuthProvider.SignInWithEmailAndPasswordAsync(ConfigSvc.Username, ConfigSvc.Password).Result);
Console.Log(AuthSvc.Auth.User.IsEmailVerified); # returns False;
User user = await AuthSvc.AuthProvider.GetUserAsync(AuthSvc.Auth.FirebaseToken);
Console.Log(user.IsEmailVerified); # returns True;
```
Cheers.

**Comment by aboyezen** [comment]
any one solve this problem
