### ISSUE TITLE
I can't install this from nuget package.

### ISSUE THREAD

**Issue by pavinan** [step-up-labs/firebase-authentication-dotnet#23]
Could not install package 'FirebaseAuthentication.net 2.2.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by bezysoftware** [comment]
Turns out it's not that ease to target profile 259 due to missing HttpClient. If you can do a PR that will somehow get around it, I will merge it
