### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by lou8566** [step-up-labs/firebase-authentication-dotnet#28]
I cannot install this package, I have tried .net 2.0 and .net 4.5

Install-Package : Could not install package 'FirebaseAuthentication.net 3.0.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v2.0',
 but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  FirebaseAuthentication.net
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

Install-Package : Could not install package 'FirebaseAuthentication.net 3.0.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5',
 but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  FirebaseAuthentication.net
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by bezysoftware** [comment]
.net 2.0 isn't supported. But I just tried 4.5 in VS2017 and it worked. What VS / nuget version do you use? It might require you to upgrade

**Comment by lou8566** [comment]
I updated my nuget version, that did the trick, Thank you
