### ISSUE TITLE
Keep me logged in functionality

### ISSUE THREAD

**Issue by E4est** [step-up-labs/firebase-authentication-dotnet#32]
I'm creating an app in Xamarin with this library. I want a user to stay logged in, even after the app is closed.
Is FirebaseAuthentication.net capable of this? If yes, what should I save to re-authenticate at next start?
I know, I could just save email and password, but I also provide the ability to login with OAtuh token from Facebook and Google.
(I would of course use Xamarin.Auth, to securely save credential information.)

**Comment by E4est** [comment]
I think I found a way to do this.

        public string BackupAuthLink()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(auth);
        }

        public async Task<bool> RestoreAuthLinkAsync(string authJSON)
        {
            try
            {
                auth = Newtonsoft.Json.JsonConvert.DeserializeObject<FirebaseAuthLink>(authJSON);
                auth = await _AuthProvider.RefreshAuthAsync(auth);
                return true;
            }
            catch
            {
                return false;
            }
        }

I tested this with my app. I logged in about a month ago and was on a vacation where I didn't touch my project. Today when starting my app it looked like I was "still logged in".
Should I be concerned about any security issues by doing this or am I good to go?

**Comment by Firedragonweb** [comment]
As far as I know that's absolutely okay. Your credentials are not stored, but the refresh token, which could be invalidated on the firebase side.

**Comment by namhnz** [comment]
It is great to have a tutorial on this topic. 😃

**Comment by Kapusch** [comment]
For the record, I was doing the same as you, but I was calling "GetFreshAuthAsync()" method from the FirebaseAuthLink deserialized, and that wasn't good at all because the AuthProvider was null (not serialized ?).

I've tried with your method as well but this wasn't enough and I still don't know why.

However, I was able to refresh authentication through this code :
```
    FirebaseAuthLink authLink = new FirebaseAuthLink(validAuthProvider, deserializedAuthUser);
    FirebaseAuthLink refreshedAuthUser = await authLink.GetFreshAuthAsync();
```
