### ISSUE TITLE
Next login failed

### ISSUE THREAD

**Issue by passa1248** [step-up-labs/firebase-authentication-dotnet#34]
Hi All!
 I need help because I made one console app that start with cron job and every time it call SignInWithEmailAndPasswordAsync function. first call succeess but next fails with this exception:

`{"Exception occured while authenticating.\nUrl: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key={0}\nRequest Data: {\"email\":\"example@gmail.com\",\"password\":\"passwordSubmitted\",\"returnSecureToken\":true}\nResponse: {\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"invalid\",\n    \"message\": \"TOO_MANY_ATTEMPTS_TRY_LATER\"\n   }\n  ],\n  \"code\": 400,\n  \"message\": \"TOO_MANY_ATTEMPTS_TRY_LATER\"\n }\n}\n\nReason: Undefined"}`

this is my code:

` Firebase.Auth.FirebaseAuth fbAuth = new Firebase.Auth.FirebaseAuth();
           
                    Firebase.Auth.FirebaseAuthProvider fbAuthProvider = new Firebase.Auth.FirebaseAuthProvider(new Firebase.Auth.FirebaseConfig(_apiKey));

                    Firebase.Auth.FirebaseAuthLink auth = await fbAuthProvider.SignInWithEmailAndPasswordAsync(_username, _password);

                    _fbClient = new Firebase.Database.FirebaseClient(_baseUrl, new Firebase.Database.FirebaseOptions
                    {
                        AuthTokenAsyncFactory = () => Task.FromResult(auth.FirebaseToken),
                    }); `
Is it possible set keepAlive = false?
Thanks in advance.

**Comment by bezysoftware** [comment]
You should be storing the auth token using that to authenticate instead of constantly logging in with email & password.
