### ISSUE TITLE
Erro To login with user and password

### ISSUE THREAD

**Issue by felipeoliveirar** [step-up-labs/firebase-authentication-dotnet#35]
Hi. I didn't get to do this api works with Just user and password authentication. 

I try to do with this way;

try{

 var config = new FirebaseConfig("my api firebase");
var authProvider = new FirebaseAuthProvider(config);

var retorno = authProvider.SignInWithEmailAndPasswordAsync(user, passwd);

var retornoserver = await retorno;

                return retornoserver.FirebaseToken;
}catch(Exeption e){
retur null;
}

the e is null. I don't know what I am doing wrong. Anybody can help me?

**Comment by felipeoliveirar** [comment]
nobody?

**Comment by TFAstudio** [comment]
We have managed to get the Email/Password authentication working within the FirebaseDatabase.net package, using FirebaseAuthentication.net package.  It was not quite so straight forward, but you must ensure you have an email and password associated in the database via the Firebase Console that Google provide through their webpage.

Here is a little sample of how we did it.

<pre>
firebaseUrl = "https://YOURDATABASE.firebaseio.com/";

// The following username and password connections are created 
// in the firebase console via https://console.firebase.google.com
// For more information see https://firebase.google.com/docs/auth/web/password-auth
firebaseUsername = "firebaseuser@yourdomain.com";
firebasePassword = "PasswordCreatedOnFirebaseConsole";

// this can be found via the console
firebaseApiKey = "YourApiKey";

var auth = new FirebaseAuthProvider(new FirebaseConfig(firebaseApiKey));
// this grabs a one-off token using the username and password combination
await token = auth.SignInWithEmailAndPasswordAsync(firebaseUsername, firebasePassword);

// finally log in
var firebaseClient = new FirebaseClient(
						firebaseUrl,
						new FirebaseOptions
						{
							AuthTokenAsyncFactory = () => Task.FromResult(token.FirebaseToken)
						});
						
// now you can make your query
var results = await firebaseClient
                .Child("users")
                .OnceAsync<Models.User>();

</pre>

**Comment by bezysoftware** [comment]
Can't you use `CreateUserWithEmailAndPasswordAsync `to create the user from code, so you don't have to create it thru Firebase console?

**Comment by TFAstudio** [comment]
Yes, sorry I forgot about that process...  We just did not want to house the logic for a web service that was the interface for the data rather than allowing users through.

**Comment by felipeoliveirar** [comment]
Hi. Sorry for delay. The user is register on firebase. This firebase key I get on "google-services.json" tag api_key{ current_key}. 
I will check your steps. When I check i will confirm.

**Comment by felipeoliveirar** [comment]
Hi. I am trying to test.I included the firebase-authentication-dotnet and xamarin.firebase.auth 
but when i call FirebaseAuth appear ambiguous declaration(2 options in this case). I don't need to include the xamarin.firebase.auth in  this case?

**Comment by felipeoliveirar** [comment]
It didn't work, unfortunally. I create a new project to make a test. Just to login and load some data. but it never return from call.

 var firebaseApiKey = "my api key from google-services";

var auth = new FirebaseAuthProvider(new FirebaseConfig(firebaseApiKey));

var waitingreturn= auth.SignInWithEmailAndPasswordAsync(user, password);

var retorno = await waitingreturn; (never return from wait return)

return retorno;

**Comment by felipeoliveirar** [comment]
somebody can help me with this issue?

**Comment by bezysoftware** [comment]
I am not able to reproduce this, I have the same code in my production UWP app and it works. Can you share repro solution?

**Comment by TennisDrum** [comment]
The following code is working for me to create users with email/password authentication and then to log them in to Firebase Database:
```
using Firebase.Auth;

// declare AuthLink variable that will be used within try/catch 
        public FirebaseAuthLink createUser;

        async void CreateUser_Clicked(object sender, System.EventArgs e)
        {
            if (string.IsNullOrWhiteSpace(emailEntry.Text) || string.IsNullOrWhiteSpace(lastNameEntry.Text) || 
                string.IsNullOrWhiteSpace(firstNameEntry.Text) || string.IsNullOrWhiteSpace(passwordEntry.Text) || 
                string.IsNullOrWhiteSpace(passwordEntry2.Text))
            {
                createUserErrorLabel.Text = "One or more fields are empty. Please try again.";
                return;
            }

            if (passwordEntry.Text != passwordEntry2.Text)
            {
                createUserErrorLabel.Text = "Password confirmation field does not match.";
                return;
            }

            var firebaseUsername = emailEntry.Text;
            var firebasePassword = passwordEntry.Text;

            var auth = new FirebaseAuthProvider(new FirebaseConfig(firebaseApiKey));

            try
            {
                createUser = await auth.CreateUserWithEmailAndPasswordAsync(firebaseUsername, firebasePassword);
            }

            catch (FirebaseAuthException ex)
            {
                // App specific error handling

                if (ex.Reason.ToString() == "EmailExists")
                {
                    createUserErrorLabel.Text = "Email already exists";
                    return;

                }
                createUserErrorLabel.Text = "Some other message received";
                return;

            }

            // if you made it to here, you've successfully created a new user with email/password authentication

        }
```
To log them in:
```
       async void SignIn_Clicked(object sender, System.EventArgs e)
        {
            try
            {
                var auth = new FirebaseAuthProvider(new FirebaseConfig(firebaseApiKey));
                var firebaseUsername = userNameEntry.Text;
                var firebasePassword = passwordEntry.Text;

                // this grabs a one-off token using the username and password combination
                var token = await auth.SignInWithEmailAndPasswordAsync(firebaseUsername, firebasePassword);

                // finally log in
                // then use this FirebaseClient to send and receive data via the authenticated user
                // assumes the firebase variable has already been declared as Public
                App.firebase = new FirebaseClient(
                                        firebaseUrl,
                                        new FirebaseOptions
                                        {
                                            AuthTokenAsyncFactory = () => Task.FromResult(token.FirebaseToken)
                                        });
            }

            catch (FirebaseAuthException ex)
            {
                if (ex.Reason.ToString() == "WrongPassword")
                {
                    loginErrorLabel.Text = "Wrong Password. Please try again.";
                    loginErrorLabel.BackgroundColor = System.Drawing.Color.Yellow;

                    return;

                }

                if (ex.Reason.ToString() == "UnknownEmailAddress")
                {
                    loginErrorLabel.Text = "Unknown email. Please try again.";
                    loginErrorLabel.BackgroundColor = System.Drawing.Color.Yellow;
                    return;

                }

                if (ex.Reason.ToString() == "InvalidEmailAddress")
                {
                    loginErrorLabel.Text = "Invalid email. Please try again.";
                    loginErrorLabel.BackgroundColor = System.Drawing.Color.Yellow;
                    return;

                }

            }

            // made it through the try/catch - login was successful
            
        }

```
