### ISSUE TITLE
GetUserAsync hangs up when passed incorrect token

### ISSUE THREAD

**Issue by ghulamostafa** [step-up-labs/firebase-authentication-dotnet#36]
Not for all request the email address and password can be sent to verify and work accordingly. So the generated token is what to be used after a successful login. But using the GetUserAsync and passing a wrong token hangs up. Does not do anything and just holds on that position. No exception even.
Am I missing something?

**Comment by bezysoftware** [comment]
That shouldn't happen, I just tried it and passing in a wrong / expired token will throw an exception. Can you share repro solution?

**Comment by ghulamostafa** [comment]
I have not used this library recently so I cannot tell. I will close this issue as of now.
