### ISSUE TITLE
how can I get user uid from firebase after create new user

### ISSUE THREAD

**Issue by WaelMohammedAbed** [step-up-labs/firebase-authentication-dotnet#37]
I am using this code to create user and it works fine (using Visual Studio C# desktop application)
```
            var authProvider = new FirebaseAuthProvider(new FirebaseConfig("Firebaseapikey"));
            var auth = await authProvider.CreateUserWithEmailAndPasswordAsync("someone@example.com", "123456");
```

but how can I get user UID after create the new user, and is their onsuccess or onerror to that I can use to check if user created or something went wrong like the email is used before

**Comment by blaiser49** [comment]
User info is in auth.User
the UID would be auth.User.LocalId
