### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by bepo00** [step-up-labs/firebase-authentication-dotnet#40]
Client pc cannot sign in. Gets this expection: 
_Exception occured while authenticating.
Url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key={0}
Request Data: {"email":"email@email.email","password":"password","returnSecureToken":true}
Response: N/A
Reason: Undefined_

Same app, configuration signs in normally on another pc on another network. What is the possible cause of expection? Could this be maybe fixed by demanding ports 5228, 5229, 5230 to be opened by network admin?

**Comment by kyurkchyan** [comment]
I have the same issue, did you find the cause?
