### ISSUE TITLE
Refreshing auth token

### ISSUE THREAD

**Issue by bepo00** [step-up-labs/firebase-authentication-dotnet#42]
I have windows application that is needed to run all time. I have implemented following code to sign in: 
`auth = await authProvider.SignInWithEmailAndPasswordAsync(username, password);            
 auth.FirebaseAuthRefreshed += (s, e) => saveAuth(e.FirebaseAuth);
                
 dbClient = new FirebaseClient(url, new FirebaseOptions
                {
                    OfflineDatabaseFactory = (t, s) => new OfflineDatabase(t, s),
                    AuthTokenAsyncFactory = async () => (await auth.GetFreshAuthAsync()).FirebaseToken
                });`

Ocassionally I still get a unauthorized expection:
         https://github.com/step-up-labs/firebase-database-dotnet/issues/87 

What is the possible reason for this?

**Comment by adepierre** [comment]
This is quite old, but I think I have a similar issue. most of the time everything is fine and the refresh function is called after 1 hour, but sometimes I get some unauthorized exceptions.

As the refresh things happens only once per hour it's quite difficult to reproduce this bug, but from what I've seen, it's when an observable tries to update data from the database.
