### ISSUE TITLE
DeleteUser not found

### ISSUE THREAD

**Issue by zollodavide** [step-up-labs/firebase-authentication-dotnet#43]
I can't seem to find the DeleteUser(string idToken) method inside FirebaseAuthProvider. Any reason for it?

**Comment by zollodavide** [comment]
I have NuGet v3.0.5

**Comment by luccasclezar** [comment]
Yeah, my PR was merged on June, but I can't see the method in the library.

**Comment by zollodavide** [comment]
Thank you, I'll use the code in the meantime, and I'll be waiting for the update!

**Comment by zollodavide** [comment]
@luccasclezar for your information, AuthErrorReason.UserNotFound inside the method GetFailureReason seems not to be found either

**Comment by bezysoftware** [comment]
I just deployed the latest code to nugget, it will be available in a bit after it gets indexed
