### ISSUE TITLE
Help with Library...

### ISSUE THREAD

**Issue by ghost** [step-up-labs/firebase-authentication-dotnet#45]
Hello,

I downloaded the library but the project will not load.  I am using Visual Studio 2015.

WHat I need to do is VERY simple.  I just need to have the ability to update one value in our Firebase DB from our website.  We have written and iOS app that uses Firebase and talks to our back end server.  I am a bit rusty with my C# and cannot figure out how to use your library.  I tried implementing your example code, but it will not compile.  The editor complains and shows errors. 

I am trying to simply log into Firebase using an account we created and then update one value, but I cannot figure out how to use your library to log in... haven't even gotten to attempt to update the value.

Any help would be greatly appreciated as I have been toying around for two days with your lib.

Using your code snippet from the site on my system the compiler complains about this:

auth.FirebaseToken

auth does not have a FirebaseToken property.  That is one one a few errors I am getting. Another is that my VS does not like await.  Again, I am very rusty with my c# as I have been doing iOS development for some years now and not much c#.  May questions and issues may seem foolish, but I cannot figure it out.

Thank you for any help!!!!

**Comment by itswisdomagain** [comment]
Hi. Have you tried getting the library via nuget package manager instead of trying to build from source code?
