### ISSUE TITLE
Documentation or Examples on How to Use this Library

### ISSUE THREAD

**Issue by JohnSandala** [step-up-labs/firebase-authentication-dotnet#46]
I have created a C# wrapper over Firebase API for using basic CRUD commands.  Everything works great.  Now I need to retrieve the users Firebase Authentication "User UID" using the users email address and password that is associated with the "User UID".  From the description that you posted regarding you library it looks like I might be able to accomplish this bit of code.  Do you have any documentation, tutorials or examples on how to inject your library into my C# .Net application and utilize the functions?

Any help would be greatly appreciated.  Thanks.  John

**Comment by bezysoftware** [comment]
You can take a look at the samples or my blog posts: https://medium.com/@bezytom
