### ISSUE TITLE
Troubles with authorization

### ISSUE THREAD

**Issue by ghost** [step-up-labs/firebase-authentication-dotnet#48]
I'm having troubles authorizing requests to a firebase db. I have been able to authenticate with a simple account with user and password, as following:

```
var authProvider = new FirebaseAuthProvider(new FirebaseConfig(firebaseApiKey));
var auth = await authProvider.SignInWithEmailAndPasswordAsync("user@domain.com", "password");
```

After I retrieve the Firebase Token, I pass it along to the FireBase client constructor as described in documentation, and i'm trying to make requests:

```
var firebaseClient = new FirebaseClient("https://[DB].firebaseio.com/", new FirebaseOptions
{
    AuthTokenAsyncFactory = () => Task.FromResult(auth.FirebaseToken)
});
var groups = await firebaseClient.Child("groups").OnceAsync<dynamic>();
```

A request like this is sent to the server (i'm using fiddler to observe what happens behind the curtains):

```
GET https://[DB].firebaseio.com/groups/.json?auth=[TOKEN] HTTP/1.1
Connection: Keep-Alive
Host: settle-up-live.firebaseio.com
```
However i keep getting 401 responses, like the following:

```
HTTP/1.1 401 Unauthorized
Server: nginx
Date: Tue, 20 Feb 2018 20:02:32 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 36
Connection: keep-alive
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Strict-Transport-Security: max-age=31556926; includeSubDomains; preload

{
  "error" : "Permission denied"
}
```

For the record, i'm querying the Settle Up firebase DB, also from Step Up Labs.

**Comment by bezysoftware** [comment]
We have database rules in place which do not allow you to run any query you want. This is to protect our database being dumped / manipulated. 
So it's not a matter of just having the correct token, but the queries need to fit our rules set.

**Comment by danygarss** [comment]
Thanks for the response, is there any documentation around about what kind of queries are allowed?

**Comment by sheindel** [comment]
@bezysoftware seems like a stale issue, not really relevant to this repo, especially since the original opener deleted their account. Close?
