### ISSUE TITLE
Get Phonenumber from UserID

### ISSUE THREAD

**Issue by GOPIKRISHNAN-1992** [step-up-labs/firebase-authentication-dotnet#50]
I have done a phone number authentication in Android project. In firebase, it created a UserId for that authenticated phone number.  Now, I wanted to retrieve the phone number based on user id using asp.net web app. 

Is there any way to get the authenticated phone number from that relevant user id? I mean is there any method or property available in this DLL to retrieve authenticated phone number using user id?

Note : I am using firebase-database-dotnet for firebase database CRUD operation.

**Comment by bezysoftware** [comment]
Not currently. The library neither supports phone login, nor does it parse user's phone information. You're welcome to do a PR for this
