### ISSUE TITLE
secure a asp.net web api with firebase-authentication-dotnet

### ISSUE THREAD

**Issue by smedasn** [step-up-labs/firebase-authentication-dotnet#52]
Great lib thx for your effort in this! 
I am currently using Azure b2c for login and i also have a secured asp.net backend. I want to switch to firebase auth in my angular frontend which will be no problem. 
Unfortunately I am stuck while trying to validate the firebase jwt token from the client in my asp backend. Is this doable with this libraray?

**Comment by bezysoftware** [comment]
No, this library doesn't do any validations. It can be used by client apps wanting to authenticate against Firebase using email+password or thirdparty oauth (facebook/gmail)

**Comment by EmilAlipiev** [comment]
Hey, try this and please let me know if it is working.  I am also on that way https://www.google.de/amp/s/blog.markvincze.com/secure-an-asp-net-core-api-with-firebase/amp/

**Comment by EmilAlipiev** [comment]
@smedasn actually url above i shared works for web core api but i couldnt fine anything for web api, did you find anything yourself?
