### ISSUE TITLE
How to get a phone number from the method GetUserAsync?

### ISSUE THREAD

**Issue by sergeylopatyuk** [step-up-labs/firebase-authentication-dotnet#53]
when authenticating using a phone number, the response from firebase is as follows:

`{
    "kind": "identitytoolkit#GetAccountInfoResponse",
    "users": [
        {
            "localId": "xxxxxxxxx",
            "providerUserInfo": [
                {
                    "providerId": "phone",
                    "rawId": "+12345678",
                    "phoneNumber": "+12345678"
                }
            ],
            "lastLoginAt": "1522411438000",
            "createdAt": "1522323452000",
            "phoneNumber": "+12345678"
        }
    ]
}`

But User DTO from method GetUserAsync does not contain a phone number.

**Comment by bezysoftware** [comment]
Resolved by #54 and release as v3.0.7
