### ISSUE TITLE
Problem with auth Password and Email

### ISSUE THREAD

**Issue by spawn1986** [step-up-labs/firebase-authentication-dotnet#56]
Hi thanks for the huge efford on this project, sorry for this but i have problems with loging in firebase with password and email, when i debbug my project, it freezed when go to authProvider.SignInWithEmailAndPasswordAsync(mail, pass).Result;. please help me i didnt know if i am doing something wrong. this is my code

private async Task<FirebaseAuthLink> Authoritation()
        {
            var authConfig = new FirebaseConfig(ConfigurationManager.AppSettings["ApiKeyFirebase"]);
            _authProvider = new FirebaseAuthProvider(authConfig);
            var mail = ConfigurationManager.AppSettings["MailFirebase"];
            var pass = ConfigurationManager.AppSettings["PassFirebase"];

            return await _authProvider.SignInWithEmailAndPasswordAsync(mail, pass);
        }
        private bool Run(DatosEnvio1800 datos)
        {
            if (datos == null) return false;

            var auth = Authoritation().Result;
            var resultado = GetResultFirebase(auth, datos).Result;
            return !string.IsNullOrEmpty(resultado.Key);
        }

please help me, thanks for everything

**Comment by bezysoftware** [comment]
Don't use .Result, preferable way is to always await. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

**Comment by philipphecht** [comment]
hello everyone Like this: var auth = await authProvider.SignInWithEmailAndPasswordAsync(FirebaseEmail, FirebasePassword);

**Comment by bezysoftware** [comment]
Yes. Or just  
```var data = await authProvider.SignInWithEmailAndPasswordAsync(FirebaseEmail, FirebasePassword);```
