### ISSUE TITLE
Add Support for Language Code

### ISSUE THREAD

**Issue by bhyip23** [step-up-labs/firebase-authentication-dotnet#57]
Firebase has the ability to set a language code so that password reset emails show up in the set language.  

https://firebase.google.com/docs/auth/web/manage-users

`firebase.auth().languageCode = 'fr';`

**Comment by EmilAlipiev** [comment]
I cant find any information about in their official rest api documentation. do you know how to do it?

**Comment by bezysoftware** [comment]
I don't know of any. I can only recommend using fiddler and see how their Javascript libraries do it

**Comment by EmilAlipiev** [comment]
Do you know a quick sample JS project? i tried to build myself but it is not working somehow. can you share if you have one? i would like to also test phone authentication

**Comment by Kapusch** [comment]
Is this still relevant ?

I remember having read that language is automatically selected according to the culture of the client.

**Comment by bezysoftware** [comment]
In v4 the language is automatically detected and set
