### ISSUE TITLE
How can I add records to the FireBase database with c #?

### ISSUE THREAD

**Issue by rmzx** [step-up-labs/firebase-authentication-dotnet#59]
for example; How can I add a TextBox data to a FireBase when the button is clicked? I do not want to use it as xaml.I could not find enough resources on c # in the internet.are there any examples of sources you know

**Comment by bezysoftware** [comment]
https://medium.com/step-up-labs/firebase-c-library-5c342989ad18

Also this is a wrong repo, database is here: https://github.com/step-up-labs/firebase-database-dotnet
