### ISSUE TITLE
Email Verification flow

### ISSUE THREAD

**Issue by batrand** [step-up-labs/firebase-authentication-dotnet#6]
There is a functionality in Firebase SDK that initates [email verification for a user](https://firebase.google.com/docs/auth/web/manage-users#send_a_user_a_verification_email). There is also a field exposing whether the user has had their email verified ([firebase.User.verified](https://firebase.google.com/docs/reference/js/firebase.User)). These functionalities are either missing from the library or I can't seem to find them. If they are not implemented, are there plans for that?

**Comment by bezysoftware** [comment]
I currently don't have any plans for it, as I don't require those features in the app I'm developing, but I am open to pull requests ;)

**Comment by itswisdomagain** [comment]
Why do you want those features @batrand?
Quite swamped at the moment but I could do a PR.

Help a brother too, what's the flow of logic for the Firebase SDK email verification?

**Comment by batrand** [comment]
I was investigating the possibility of using Firebase to manage the entire user authentication flow (log in and sign up). That is, I wanted to be able to let users register for new accounts within the app, which led to the problem of handling email verification. Firebase handles this, but that feature is missing from this library.

The flow of sending the email is documented on their [documentation](https://firebase.google.com/docs/auth/web/manage-users#send_a_user_a_verification_email).

**Comment by itswisdomagain** [comment]
I like the idea of managing the entire user authentication flow from the app. Let me try to implement thoe features of the flow you talked about and I'll do a PR.

**Comment by bezysoftware** [comment]
Nice PR! It is merged, thanks!
