### ISSUE TITLE
SignInWithIdTokenAsync function using rest api?

### ISSUE THREAD

**Issue by EmilAlipiev** [step-up-labs/firebase-authentication-dotnet#60]
do you know if it is possible to do signInWithCredential function as described in the link below? because i am using your library for xamarin and mostly it works in the shared .net standard library but google sign in has exception, because google native sigin doesnt return actual access token but it returns an IdToken as jwt form created by google. I couldnt find a possibility to signin into firebase using this this IdToken, i am not sure if customtoken can work.

https://firebase.google.com/docs/auth/android/google-signin

**Comment by EmilAlipiev** [comment]
I found the answer so quickly and forked your code. if you want i can send you a PR. function would like as below according to explained [here ](https://firebase.google.com/docs/reference/rest/auth/#section-sign-in-with-oauth-credential)
```

       /// <summary>
        /// Using the provided Id token from google signin, get the firebase auth with token and basic user credentials.
        /// </summary>
        /// <param name="authType"> The auth type. </param>
        /// <param name="IdToken"> The Id token retrieved from google signin </param>
        /// <returns> The <see cref="FirebaseAuth"/>. </returns>
        public async Task<FirebaseAuthLink> SignInWithIdTokenAsync(string IdToken)
        {
            var providerId = this.GetProviderId(FirebaseAuthType.Google);
            var content = $"{{\"postBody\":\"id_token={IdToken}&providerId={providerId}\",\"requestUri\":\"http://localhost\",\"returnSecureToken\":true}}";

            return await this.ExecuteWithPostContentAsync(GoogleIdentityUrl, content).ConfigureAwait(false);
        }
```

**Comment by EmilAlipiev** [comment]
I hardcoded as google because i didnt see Idtoken is used beside google because facebook api returns access token as in the documentation but it can be also dynamic like your access token function

**Comment by bezysoftware** [comment]
Sure, make it a PR and I'll merge it. Just rename the method to make it clear it's google only, something like SignInWithGoogleIdTokenAsync
