### ISSUE TITLE
How do you use RefreshAuthAsync?

### ISSUE THREAD

**Issue by EmilAlipiev** [step-up-labs/firebase-authentication-dotnet#62]
when I see your implementation for RefreshAuthAsync, you are passing FirebaseAuth object, does it mean that we should store this object in the app because once it is expired, it will not be returned I believe, in your sample project, it seems like that you pass it null. How is the good usage of this? because I only saved refreshtoken and firebasetoken in my app. 

```

  public async Task<FirebaseAuthLink> RefreshAuthAsync(FirebaseAuth auth)
        {
            var content = $"{{\"grant_type\":\"refresh_token\", \"refresh_token\":\"{auth.RefreshToken}\"}}";
            var responseData = "N/A";

            try
            {
                var response = await this.client.PostAsync(new Uri(string.Format(GoogleRefreshAuth, this.authConfig.ApiKey)), new StringContent(content, Encoding.UTF8, "application/json"));

                responseData = await response.Content.ReadAsStringAsync();
                var refreshAuth = JsonConvert.DeserializeObject<RefreshAuth>(responseData);

                return new FirebaseAuthLink
                {
                    AuthProvider = this,
                    User = auth.User,
                    ExpiresIn = refreshAuth.ExpiresIn,
                    RefreshToken = refreshAuth.RefreshToken,
                    FirebaseToken = refreshAuth.AccessToken
                };
            }
            catch (Exception ex)
            {
                throw new FirebaseAuthException(GoogleRefreshAuth, content, responseData, ex);
            }
        }
```

**Comment by bezysoftware** [comment]
Yes you should save that object each time a token is refreshed. 
So after you `SignIn...()` you should then save the `FirebaseAuth `object and subscribe to `FirebaseAuthRefreshed` event, where you save the `FirebaseAuth `object as well.
When your app restarts you should then create the `FirebaseAuth `object from your storage and using this and the `FirebaseAuthProvider `create the `FirebaseAuthLink` object, which can be used to get fresh access tokens.
