### ISSUE TITLE
How to implement/add support for Token cache

### ISSUE THREAD

**Issue by AndreasSchmid1** [step-up-labs/firebase-authentication-dotnet#65]
Is it possible to store a token on the filesystem so the user does not need to login everytime the application is started?

**Comment by cabauman** [comment]
Yes, just serialize the whole FirebaseAuth object and save it to your local storage (whatever that may be). That will save the Firebase token, the validity period, refresh token, etc.

    string json = JsonConvert.SerializeObject(firebaseAuth);
    localStorage.Save("firebase_auth_json", json);
    
    // Next time you start your app...
    string json = localStorage.Load("firebase_auth_json");
    FirebaseAuth  auth = JsonConvert.DeserializeObject<FirebaseAuth>(json);
    var authProvider = new FirebaseAuthProvider(new FirebaseConfig(Config.ApiKeys.FIREBASE));
    FirebaseAuthLink  authLink = new FirebaseAuthLink(authProvider, auth);
