### ISSUE TITLE
auth.SendEmailVerificationAsync doesn't work

### ISSUE THREAD

**Issue by marciliocarvalho** [step-up-labs/firebase-authentication-dotnet#66]
I would like to know how the auth.SendEmailVerificationAsync method works because I am not able to send the confirmation email.

**Comment by marciliocarvalho** [comment]
I would like to know how can I create an authentication account on Firebase only after email confirmation

**Comment by bezysoftware** [comment]
You can see how it works by looking at the source code: https://github.com/step-up-labs/firebase-authentication-dotnet/blob/master/src/Firebase.Auth/FirebaseAuthProvider.cs#L199

What do you mean it doesn't work? The code throws exception? Email doesn't arrive? "doesn't work" is not very useful
