### ISSUE TITLE
FirebaseDatabase.net used in Xamarin

### ISSUE THREAD

**Issue by marciliocarvalho** [step-up-labs/firebase-authentication-dotnet#69]
I'm using FirebaseDatabase.net on Xamarin. However, when I try to use the line of code:

token = await auth.SignInWithEmailAndPasswordAsync (email, password);

The graphical interface hangs. Could someone tell me why?

**Comment by angelru** [comment]
@marciliocarvalho try this...

auth = await auth.SignInWithEmailAndPasswordAsync (email, password);

await auth.RefreshUserDetails();

//do thing
