### ISSUE TITLE
Refresh Tokens

### ISSUE THREAD

**Issue by iwantadventureinthegreatwidesomewhere** [step-up-labs/firebase-authentication-dotnet#70]
This question is built around the previously addressed issue found here:
https://github.com/step-up-labs/firebase-authentication-dotnet/pull/14

I'm fairly new to c# and to implementing this package in code, so my questions may seem primitive.

Could someone explain to me how SaveAuth works? It does not seem to be contained within this package so I assume it is custom. It takes the FirebaseAuthLink "auth" as parameter after using the return of the SignInWithOAuthAsync method, but later takes a FirebaseAuth for the event. An existing snippet of SaveAuth would help. Thank you for your time.

P.S. great package, super easy work with :)

**Comment by maltezc** [comment]
Were you able to figure this out? I'm running into the same issue of not knowing how to store the auth locally.
