### ISSUE TITLE
Support for Firestore

### ISSUE THREAD

**Issue by premy** [step-up-labs/firebase-authentication-dotnet#74]
I'm connecting to Firestore with the Google.Cloud.Firestore library. If I'd use your library to create users (email+password), would I be able to authenticate them in Firestore or would this only be possible in RTDB?

**Comment by bezysoftware** [comment]
You can try and let us know :) But I think it should work

**Comment by angelru** [comment]
@premy  I'm interested, did you try?

**Comment by premy** [comment]
Hi, yes I did but it didn't go too well (sorry, don't remember details anymore). Ended up doing it this way after endless research:
Dim credential As GoogleCredential = GoogleCredential.FromFile(Server.MapPath("key_firestore.json"))
        Dim channelCredentials As ChannelCredentials = credential.ToChannelCredentials()
        Dim channel As Channel = New Channel(FirestoreClient.DefaultEndpoint.ToString(), channelCredentials)

        Dim fsClient As FirestoreClient = FirestoreClient.Create(channel)
        Dim db As FirestoreDb = FirestoreDb.Create("forlifesaude-ec392", client:=fsClient)

This connects me and then I can go like:

Adding a record:
Dim Patient As New FBASE.Paciente With {
                    .Nome = "John Doe",
                    .DOB = #01/01/1980#,
                    .Address = "Casa",
                    .Bairro = "Rio de Janeiro"
           }

        
        Dim collection As CollectionReference = db.Collection("Pacientes")
         Dim document As DocumentReference = Await collection.AddAsync(Patient)

      Or query a collection:
   Dim patients As QuerySnapshot = Await collection.GetSnapshotAsync()

Got a lot of help from the  Google.Cloud.Firestore docs
