### ISSUE TITLE
RefreshAuthAsync mis-parses returned token

### ISSUE THREAD

**Issue by phsumi** [step-up-labs/firebase-authentication-dotnet#78]
I'm trying to get a new token based on a Firebase refresh token like this:

        public async Task<FirebaseAuthLink> Login(string refreshToken)
        {
            using (var authProvider = new FirebaseAuthProvider(new FirebaseConfig(ApiKey)))
            {
                Firebase.Auth.FirebaseAuth auth = new Firebase.Auth.FirebaseAuth() {RefreshToken = refreshToken};
                return await authProvider.RefreshAuthAsync(auth);
            }
        }

The problem is that this library does invoke the Google refresh endpoint, but when parsing the returned JSON, it checks for the presence of an `acccess_token`, when Firebase returns the new token as an `id_token`.
https://firebase.google.com/docs/reference/rest/auth/#section-refresh-token

Accordingly, the token is being returned and the `AccessToken` property is null.

I don't know whether there are cases where `access_token` would be right, but the spec I posted seems to be up-to-date (I'm currently using that endpoint in Javascript), so it looks as if `RefreshAuth` should have a property like this instead:

    [JsonProperty("id_token")]
    public string IdToken { get; set; }

**Comment by bezysoftware** [comment]
There is a whole discussion about refreshing the access token - https://github.com/step-up-labs/firebase-authentication-dotnet/issues/7 
From what I remember, access_token token is always returned. 
And I used this as reference: https://developers.google.com/identity/toolkit/reference/securetoken/rest/v1/token
