### ISSUE TITLE
Creating user with email/password

### ISSUE THREAD

**Issue by Ralim** [step-up-labs/firebase-authentication-dotnet#8]
Hi,
Sorry to be a pest...
Any chance of a guide on how to create a user with a email/password?

Currently I have the following:

```
_firebaseAuth = new FirebaseAuthProvider(new FirebaseConfig("<Web API Key>"));
var resp = _firebaseAuth.CreateUserWithEmailAndPasswordAsync(email, password);
			resp.Wait();//we need the response
```

Looking in the debugger, it hangs on the `Wait()` as long as I have had the patience to wait.

Any ideas on where I should go next / How to debug?
Is there somewhere I need to give the firebase URL to auth against?
Thank you :)
(The rest of the library appears to work perfectly)!

**Comment by bezysoftware** [comment]
Don't use wait, use the combination of `async/await` keywords introduced in C# 6.
https://msdn.microsoft.com/en-us/library/hh156528.aspx

**Comment by Ralim** [comment]
I dont see how to use the `async/await` to create a blocking method?
Or do I have to use callbacks to pass the answer out ?
... Sorry for lack of knowledge, from procedural C background....

**Comment by bezysoftware** [comment]
Yes, each time you want to use `await`, your method must also be `async`
