### ISSUE TITLE
SignInWithOAuth does not return a refresh token

### ISSUE THREAD

**Issue by Seehle** [step-up-labs/firebase-authentication-dotnet#85]
Hi

I'm using this package in a Xamarin Forms app, I'm able to retrieve a refresh token when i'm signing in via email & password, and I'm able to verify the returned token on my secured API, this however is not the case when i'm signing in with oAuth, firstly the RefreshToken is null and the returned FirebaseToken gives me a forbidden exception when i'm verifying it against the same secured API. Is there some special consideration required for SignInWithOauth?

**Comment by Seehle** [comment]
I discovered that this happens when you've prevented the creation of multiple accounts with the same email address on Firebase, so when your email is already associated with the Google provider, and you're trying to signin with Facebook, the Firebase SDKs would throw an exception stating that the email is already linked to another provider, but this package returns successfully with the refresh token missing and an invalid Firebase token with no expiry date. Can I make the assumption that if the refresh token is missing, then this is the only issue that could be the cause?

**Comment by EmilAlipiev** [comment]
here there is stackoverflow question, you can follow up. it has nothing to do with this package but it is general firebase issue. it looks like before it used to return an error message that account exist but like you said it doesnt return error any longer. it is hard to understand that it is existing account. if we can understand that account exist, we need to do account linking function to link accounts.

https://stackoverflow.com/questions/55997335/how-to-link-facebook-account-with-existing-email-google-account-on-firebase

**Comment by jd-alexander** [comment]
Hello, anyone figured out a solve for this?

**Comment by bezysoftware** [comment]
Did you configure your firebase project to support  Google / Facebook auth?
