### ISSUE TITLE
FirebaseAuthRefreshed not fire

### ISSUE THREAD

**Issue by lumisoftusa** [step-up-labs/firebase-authentication-dotnet#87]
Hi,

I am using this library one issue i am facing is that firebase token expires in an hour and there is an event FirebaseAuthRefreshed i used that event to refresh token but it does not work and when token expires my app does crashed.
Please guide me the solution  i have a lot of Subscribe events in my project but during expiration app crashed and auto refresh token event does not work.

Regards

**Comment by EmilAlipiev** [comment]
you should use to check FirebaseAuth.IsExpired()
if this one is true then you should call 

```
    var authProvider = new FirebaseAuthProvider(new FirebaseConfig(FirebaseApiKey));
    var refreshedUser = await authProvider.RefreshAuthAsync(FirebaseAuth);
```

you have to also make sure that FirebaseAuth.RefreshToken is not null or empty string. 
I hope this helps you.

**Comment by bezysoftware** [comment]
No, you should be calling `GetFreshAuthAsync` which checks the token validity and refreshes it if needed. It will then also raise the refreshed event.

https://github.com/step-up-labs/firebase-authentication-dotnet/blob/master/src/Firebase.Auth/FirebaseAuthLink.cs#L80
