### ISSUE TITLE
Anonymous authentication

### ISSUE THREAD

**Issue by steveharan** [step-up-labs/firebase-authentication-dotnet#9]
How can you do an anonymous authentication?  Thanks

**Comment by dnishimoto** [comment]
It is not possible
You need to authenticate using Oauth, Facebook, or firebase use email and password

**Comment by steveharan** [comment]
OK, so if I have an app where I want to retrieve some data not based on a specific user, but app level, which is the best way to do that?

**Comment by steveharan** [comment]
Figured it - thanks!

**Comment by steveharan** [comment]
I can read with anonymous authentication, but I cannot write.  My rules are set up correctly:

```
  "rules": {
   ".read": "auth != null",
    ".write": "auth != null",
  }
```



```
            var auth = await authProvider.SignInAnonymouslyAsync();

            var firebase = new FirebaseClient("https://ownerportal-61402.firebaseio.com/");

            var newMsg = await firebase
              .Child("104837")
              .WithAuth(auth.FirebaseToken)
              .OnceAsync<bool>();


```           
...works but this does not (get a 401 unauthorised)

```
 var result = await firebase
                .Child("343434")
                .WithAuth(auth.FirebaseToken)
                .PostAsync(new { newMessage = true });
```

I feel I'm very close!

**Comment by bezysoftware** [comment]
I suspect it's the same issue as this one: https://github.com/step-up-labs/firebase-database-dotnet/issues/22#issuecomment-259654302 
Don't use .WithAuth, it will be depricated and eventually removed. Instead use FirebaseOptions to specify where the token should come from (as describe in the linked post)

**Comment by steveharan** [comment]
FirebaseOptions doesn’t exist in FirebaseClient

8-(

**Comment by CarterMiller** [comment]
I'm having the same issue as **steveharan**, but with VB.NET

.withAuth doesn't appear to be available, and I can't see how to use FirebaseOptions

**Comment by steveharan** [comment]
I ended up using firebase auth and restsharp once authenticated...

https://github.com/step-up-labs/firebase-database-dotnet/issues/22

**Comment by bezysoftware** [comment]
Use v2.0.1 of FirebaseDatabase, FirebaseOptions are available there. There are also samples showing how they can be used
