### ISSUE TITLE
How to use the login with email and password function

### ISSUE THREAD

**Issue by 28718224** [step-up-labs/firebase-authentication-dotnet#91]
Hi i am able to connect to my firebase with the API key but i am unsure on how i would use my email and password tom login to the firebase. I used something similiar for my mobile app and would like to do the same with a wpf application but i am not sure how. 
I would like to use these methods 
CreateUserWithEmailAndPassword
SignInWithEmailAndPassword
SendPasswordResetEmail
If anybody could please present me with an example of how to do this I would very much appreciate it

**Comment by bezysoftware** [comment]
What isn't clear about these methods? You can use them like these:

```csharp
var authProvider = new FirebaseAuthProvider(new FirebaseConfig(FirebaseAppKey));
var link = await authProvider.CreateUserWithEmailAndPasswordAsync("email", "password");
link.User // user info
link.FirebaseToken // access token
```

**Comment by poepoe12002** [comment]
> 
> 
> What isn't clear about these methods? You can use them like these:
> 
> ```cs
> var authProvider = new FirebaseAuthProvider(new FirebaseConfig(FirebaseAppKey));
> var link = await authProvider.CreateUserWithEmailAndPasswordAsync("email", "password");
> link.User // user info
> link.FirebaseToken // access token
> ```

Crystal clear.  Right after that is where I am having a problem.  I can't find anything analogous to 'SendEmailVerification()'.  Please point me in the right direction.  Thanks.

**Comment by Molebatsi** [comment]
@poepoe12002 CreateUserWithEmailAndPasswordAsync has an optional parameter sendVerificationEmail which is false by default, so you'll have to set it to true if you want to send the verification email i.e. CreateUserWithEmailAndPasswordAsync("emailAddress","password","displayname",true);

Hope this helps

**Comment by poepoe12002** [comment]
@Molebatsi 'CreateUserWithEmailAndPasswordAsync' doesn't give me that option.  I'm using FirebaseAuthentification.net v 4.0.0-alpha.2.  Perhaps things have changed.  What version are you referring to?

**Comment by Molebatsi** [comment]
@poepoe12002 you are right, checked the source for v4 and CreateUserWithEmailAndPasswordAsync doesn't have the mentioned parameter. I'm using version 3.4.0

**Comment by poepoe12002** [comment]
@Molebatsi Thanks, I'll look a while longer in V4 for the answer before I think about shifting directions.
