### ISSUE TITLE
Exception occured while authenticating

### ISSUE THREAD

**Issue by spartacus04** [step-up-labs/firebase-authentication-dotnet#93]
I tried using the email and password login for firebase but i get this exception:
Firebase.Auth.FirebaseAuthException: 'Exception occured while authenticating.
Url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key={0}

what can i do?

**Comment by somedudefrominternet** [comment]
Hey @spartacus04 what was the issue in your case and how did you resolve it?
