### ISSUE TITLE
Can't get it to work in vb.net?

### ISSUE THREAD

**Issue by cslak** [step-up-labs/firebase-authentication-dotnet#95]
Ive been trying to get this to work on vb.net with no luck. Any examples? I'm as far as here:
  Private Async Function SurroundingSubAsync() As Task
        Dim authProvider = New FirebaseAuthProvider(New FirebaseConfig("myfirebase api"))
        
        Dim auth = Await authProvider.SignInWithEmailAndPasswordAsync("test@test.com", "test123")
        Dim firebase = New FirebaseClient("https://vbtest-5454.firebaseio.com/", New FirebaseOptions With {
        .AuthTokenAsyncFactory = Function() Task.FromResult(auth.FirebaseToken)
    })
        Dim dinos = Await firebase _
            .Child("dinosaurs") _
            .OrderByKey() _
            .StartAt("pterodactyl") _
            .LimitToFirst(2) _
            .OnceAsync(Of Dinosaur)
        For Each dino In dinos
            Console.WriteLine($"{dino.Key} is {dino.Object.Height}m high.")
        Next
    End Function

Nothing works, no errors, just doesn't do anything and hangs, tried using:
     Dim auth = Await authProvider.CreateUserWithEmailAndPasswordAsync("test@test.com", "test123")
Nothing gets created, not  sure what im doing wrong. Some help would be apreciated.

**Comment by bezysoftware** [comment]
Can you try cloning the repository and stepping through the code ?
