### ISSUE TITLE
How do you login with email and password?

### ISSUE THREAD

**Issue by alexbgameson** [step-up-labs/firebase-authentication-dotnet#96]
Please provided example usage with how to handle response from firebase auth.

**Comment by bezysoftware** [comment]
There are methods `SignInWithEmailAndPasswordAsync` and `CreateUserWithEmailAndPasswordAsync` which you can use

**Comment by alexbgameson** [comment]
Methods are of no use if you dont know how to properly use them. Please
provide the usage of those two methods.

**Comment by bezysoftware** [comment]
Some samples can be found here: https://medium.com/step-up-labs/firebase-authentication-c-library-8e5e1c30acc2

Essentially it should be 

```csharp
var ap = new FirebaseAuthProvider(new FirebaseAuthConfig("<YOUR APP API KEY>"));
var auth = await ap.SignInWithEmailAndPasswordAsync("email", "password");
```

**Comment by alexbgameson** [comment]
Thank you very much. One last thing. How do you handle a successful
authentication?

**Comment by penielx** [comment]
How do you handle a successful authentication?

**Comment by bezysoftware** [comment]
That's up to every developer. In my apps I serialize & store the auth object and restore it after app restart. Then I use the the auth's `GetFreshAccessToken` method in `FirebaseDatabase.net` to access our protected database resources. Same for `FirebaseStorage.net`.

I'm currently rewriting the Auth library to have this more automated, with built-in UI for WPF, UWP and Xamarin (similar to FirebaseUI), but it still a lot of work to be done

**Comment by JesusZorrilla** [comment]
Por favor realice un ejemplo de las credenciales de inicio de sesión y registro de usuario mas reiniciar la contraseña

**Comment by KairoMartins18** [comment]
please write a complete example on the subject

**Comment by bezysoftware** [comment]
Check out v4, it should have more samples: https://github.com/step-up-labs/firebase-authentication-dotnet/tree/feature/v4
