### ISSUE TITLE
 Hello my dear friend

### ISSUE THREAD

**Issue by mesut25** [step-up-labs/firebase-authentication-dotnet#99]
api. getting error downloading. download stops. (visual basıc 2015)
I like to work with students and simple examples. I'm working on vb.net. I do not know english. I'll be glad, if you help me.
a question Do you consider creating a firebase .dll in small printer.

https://smallbasic-publicwebsite.azurewebsites.net/

![1](https://user-images.githubusercontent.com/31391850/70991089-7b77f680-20cf-11ea-99aa-4a59eef5b2a7.png)

**Comment by bezysoftware** [comment]
You need to at least target .NET Framework 4.6.1, or higher

**Comment by mesut25** [comment]
i'll try it thanks.
How to install your (FirebaseDatabase.net) package in 2010 etc.

I'm a beginner thanks

![1](https://user-images.githubusercontent.com/31391850/71313558-0005a480-2443-11ea-99ba-606b1a2387be.png)

**Comment by bezysoftware** [comment]
You need to install it via nuget. I don't know the vs2010 interface, I can only suggest using vs 2019, their community edition is free

**Comment by mesut25** [comment]
I tried to install it but the error persists

download and test steps
![1](https://user-images.githubusercontent.com/31391850/71356422-d8b9ef00-258a-11ea-899a-566cbfd8ce9f.png)
![2](https://user-images.githubusercontent.com/31391850/71356434-e40d1a80-258a-11ea-8f2e-ac3cfbd34e8d.png)
![3](https://user-images.githubusercontent.com/31391850/71356460-f7b88100-258a-11ea-8aa0-e19bed3aa804.png)

**Comment by bezysoftware** [comment]
Did you change the target framework in your project?
